version: "3.8"
services:
  mntr-db:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_PASSWORD: mntr
      POSTGRES_USER: mntr
      POSTGRES_DB: mntr
    volumes:
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: pg_isready -U mntr -d mntr
      interval: 10s
      timeout: 3s
      retries: 10
  mntr-server:
    build: server
    container_name: mntr-server
    ports:
      - 8080:8080
    depends_on:
      mntr-db:
        condition: service_healthy
    environment:
      DB_HOST: mntr-db
      DB_USER: mntr
      DB_PASSWORD: mntr
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/services" ]
      interval: 10s
      timeout: 5s
      retries: 10
  mntr-client:
    build: client
    container_name: mntr-client
    ports:
      - 3000:3000
    depends_on:
      mntr-server:
        condition: service_healthy