version: "3.7"
services:
  mntr-db:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_PASSWORD: mntr
      POSTGRES_USER: mntr
      POSTGRES_DB: mntr
    volumes:
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init.sql
  mntr-server:
    build: server
    container_name: mntr-server
    ports:
      - 8080:8080
    depends_on:
      - mntr-db
    environment:
      DB_HOST: mntr-db
      DB_USER: mntr
      DB_PASSWORD: mntr
  mntr-client:
    build: client
    container_name: mntr-client
    ports:
      - 3000:3000
    depends_on:
      - mntr-server