version: "3.7"
services:
  db:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_PASSWORD: mntr
      POSTGRES_USER: mntr
      POSTGRES_DB: mntr
    ports:
      - 5432:5432
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql